
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aws-nginx
  description: Creates an instance in AWS.

  tags:
    - tosca
  links:
    - url: http://15.222.73.170/console/page/blueprints_blueprint/aws-nginx?c=%5B%7B%22context%22%3A%7B%7D%7D%2C%7B%22context%22%3A%7B%22blueprintId%22%3A%22aws-nginx%22%7D%2C%22pageName%22%3A%22aws-nginx%22%7D%5D#!
      title: Deploy component
      icon: user
spec:
  type: service
  lifecycle: production
  owner: team-a
